64 resource system
wynn-rj/sword-and-bored-game pull request #116
Opened 2020-02-16 00:36 UTC by Kuczek8

Changes proposed in this pull request:
- Created  basic resource system

2020-02-17 23:57 UTC, cthomas68 commented
Looks good. This isn't so important but as for coding style, make public members and methods Pascal Case. And then I don't think all of the comments are necessary

2020-02-19 20:01 UTC, wynn-rj requested changes
Simple and clear but code quality needs to be impoved

2020-02-19 20:01 UTC, wynn-rj commented on Assets/Scripts/Strategy/GameResources/Gold.cs
> +            if (payment.cost <= amount)
You can just return this value

2020-02-19 20:01 UTC, wynn-rj commented on Assets/Scripts/Strategy/GameResources/Gold.cs
> +        public int amount { get; set; }
This should start with a capital A

2020-02-19 20:01 UTC, wynn-rj commented on Assets/Scripts/Strategy/GameResources/Gold.cs
> +        }
This method isn't useful since amount is public

2020-02-19 20:01 UTC, wynn-rj commented on Assets/Scripts/Strategy/GameResources/IPayment.cs
> +        int cost { get; set; }
These should be Pascal Case

2020-02-19 20:01 UTC, wynn-rj commented on Assets/Scripts/Strategy/GameResources/IResource.cs
> +
Bad spacing

2020-02-19 20:01 UTC, wynn-rj commented on Assets/Scripts/Strategy/GameResources/IResource.cs
> +        int amount { get; set; }
Pascal case

2020-02-19 20:01 UTC, wynn-rj commented on Assets/Scripts/Strategy/GameResources/IResource.cs
> +         */
These comments don't add anything, the doc based comments are identified with a `///`

2020-02-19 20:01 UTC, wynn-rj commented on Assets/Scripts/Strategy/GameResources/Payment.cs
> +        // The amount of resource needed to complete the purchase
These comments should only be defined in the interface

2020-02-24 01:54 UTC, closed without merging