76 ui stats battles
wynn-rj/sword-and-bored-game pull request #91
Opened 2020-02-10 04:38 UTC by Toeecko

Fixes #58 
Fixes #75 
Fixes #76 

Changes proposed in this pull request:
- Creates character factory
- Creates db
- Creates ORM
- Creates StatsUI

2020-02-10 05:14 UTC, ThBrokenToaster submitted a review, later dismissed

2020-02-10 17:55 UTC, wynn-rj requested changes

2020-02-10 17:55 UTC, wynn-rj commented on Assets/Scripts/Battlefield/CreatureScripts/UnitStats.cs
> +        public string role;
This file should be removed. We already have an interface and class for this and this was not part of these issues tasking. I am willing to accept this PR with these changes as long as there is a high priority issue created for next timebox focused on removing this

2020-02-10 17:55 UTC, wynn-rj commented on Assets/Scripts/Battlefield/Camera/CameraManager.cs
> +        public List<GameObject> cameras = new List<GameObject>();
Why was this changed? This seems to serve no purpose

2020-02-10 17:55 UTC, wynn-rj commented on Assets/Scripts/Battlefield/TurnMechanism/TurnManager.cs
> +        public List<GameObject> units = new List<GameObject>();
Why was this changed? This seems to serve no purpose

2020-02-10 17:55 UTC, wynn-rj commented on Assets/Scripts/Battlefield/CreatureScripts/UnitAbilitiesContainer.cs
> +        public List<AbstractAbilitySO> abilities = new List<AbstractAbilitySO>();
Why was this changed? This seems to serve no purpose

2020-02-10 17:55 UTC, wynn-rj commented on Assets/CharacterFactory.cs
> +}
This should create an object that extends an `ICharacter`, with a `GameObject` that wraps around that. There is no reason this should be implemented as a separate class. Everything from the database should be pulled into one of the data-based classes and then `GameObjects` should wrap those

2020-02-10 17:56 UTC, wynn-rj commented
Overall the database side looks good, but I am very confused why the classes designed for interacting with the database were not used. If you have a good reason for this I am willing to accept this as long as an issue is created to fix this in the next timebox

2020-02-10 18:03 UTC, wynn-rj requested changes
An additional this is all of the table class implement the same functionality, so they should all extend a shared interface

2020-02-10 18:03 UTC, wynn-rj commented on Assets/CharacterFactory.cs
> +
No namespace is given. Also this should ***not*** be on the root folder Assets

2020-02-10 18:03 UTC, wynn-rj commented on Assets/Scripts/GameData/Database/UnitFromDatabase.cs
> +
No namespace

2020-02-10 21:38 UTC, wynn-rj commented on Assets/Scripts/Battlefield/CreatureScripts/UnitStats.cs
> +        public string role;
Will be fixed in #93

2020-02-10 21:38 UTC, wynn-rj commented on Assets/CharacterFactory.cs
> +}
Will be fixed in #93

2020-02-11 00:29 UTC, ThBrokenToaster approved these changes
*Thumbs Up* Good character spawning

2020-02-11 00:32 UTC, wynn-rj approved these changes

2020-02-11 00:32 UTC, merged