62 hex movement
wynn-rj/sword-and-bored-game pull request #95
Opened 2020-02-10 21:02 UTC by Kuczek8

Fixes #62 

Changes proposed in this pull request:
- Basic character movement
- Edited hex map to be smaller and flat and all of type plains tile
- Enemy on map that moves towards player

2020-02-10 21:10 UTC, wynn-rj requested changes

2020-02-10 21:10 UTC, wynn-rj commented on Assets/Scripts/Strategy/Movement/PlayerMove.cs
> +            if (Physics.Raycast(ray, out hit, 10000))
That seems like an arbitrarily long raycast

2020-02-10 21:17 UTC, wynn-rj commented on Assets/Scripts/Strategy/Movement/PlayerMove.cs
> +            if (Physics.Raycast(ray, out hit, 10000))
Fixed in de44f89

2020-02-10 21:17 UTC, wynn-rj approved these changes

2020-02-11 00:16 UTC, cthomas68 approved these changes
Looks good.

2020-02-11 00:33 UTC, merged